### ISSUE TITLE
Missing final state check

### ISSUE THREAD

**Issue by ruckustboom** [sammontakoja/KotlinTestVersusJUnit#1]
Shouldn't there be another state check after this line to make sure it's still disarmed?

https://github.com/sammontakoja/KotlinTestVersusJUnit/blob/2f50ef489d0ac703ff436ab1ae66ee6aa6934d23/kotlintest/src/test/kotlin/BombSpec.kt#L52

**Comment by sammontakoja** [comment]
You are right, thanks. 
Added missing state check.
